import ReduxProvider from "@/redux/ReduxProvider";
import { AuthProvider } from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import AnotherProvider from "@/redux/AnotherProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  return (
          <AuthProvider>
            <ReduxProvider>
           
                <html lang="en" data-theme="light">
                  <body className={inter.className}>
                            {children}
                  </body>
                </html>
            
            </ReduxProvider>
          </AuthProvider>
  );
}
